### ISSUE TITLE
Do preliminary planning

### ISSUE THREAD

**Issue by jnguyen9763** [khoanguyen52/dashboard#1]
## Description

Write down what this project should encompass:

- How do we want to save view?
  - Save it locally --> indexeddb
  - Save it on firebase --> require a login flow

- Sketch out what your project would look like
  - Open up to login flow? or open up to tutorial? or just open up to an empty dashboard?
  - How does adding widgets look? How does deleting work? 
  - Settings? for each kind of widget? for overall dashboard?

### Basics

- Be able to save our view
- Add widgets
- Remove widgets
- Configure widgets
- Move and lock widgets
- Configure overall settings??
- At least 5 widgets: clock, calendar, weather, search bar, and quote
- **Responsiveness**
- **UX aspect** (how do would a user know their view is saved?)

### Advanced

- Tutorial??
- More widgets? Gallery? 
- Multiple dashboards??

## Resources

https://jnguyen9763.github.io/dashboard/

https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca

**Comment by khoanguyen52** [comment]
https://docs.google.com/document/d/e/2PACX-1vQGgI4-mp_dr01vongIlS2aYd7dFsk_1uGRI8zcJexrr__B7cBZa1Hv_8EWVIKhEGXFbEL6qi5jitsR/pub

**Comment by khoanguyen52** [comment]
https://docs.google.com/document/d/e/2PACX-1vQGgI4-mp_dr01vongIlS2aYd7dFsk_1uGRI8zcJexrr__B7cBZa1Hv_8EWVIKhEGXFbEL6qi5jitsR/pub
